name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version}}
    # Setup key
      - run: set -eu
      - run: mkdir "$HOME/.ssh"
      - run: echo "${{ secrets.key }}" > "$HOME/.ssh/key"
      - run: chmod 600 "$HOME/.ssh/key"
    # Build
      - run: npm ci
      - run: npm run build
    # Deploy
      - run: cd build && rsync -e "ssh -p 22 -i $HOME/.ssh/key -o StrictHostKeyChecking=no -o KexAlgorithms=diffie-hellman-group14-sha1" --archive --progress --compress --delete . root@80-78-247-137.cloudvps.regruhosting.ru:/home/apps/QuadOps-map

# cd build && rsync -e "ssh -p 22 -i $HOME/.ssh/key -o StrictHostKeyChecking=no -o KexAlgorithms=diffie-hellman-group14-sha1" --archive --compress --delete . root@80-78-247-137.cloudvps.regruhosting.ru:/home/apps/QuadOps-map

# ssh -p 22 -vvvv -i $HOME/.ssh/key -o StrictHostKeyChecking=no -o KexAlgorithms=diffie-hellman-group14-sha1 root@80-78-247-137.cloudvps.regruhosting.ru